### ISSUE TITLE
Dask memory mapping error with large dataset

### ISSUE THREAD

**Issue by kdmarchuk** [micro-manager/pycro-manager#350]
Hi Henry, 

I have a SPIM dataset of 545 GB and am getting 

`OSError: [WinError 8] Not enough memory resources are available to process this command`

The error occurs at this line
```
magellan = Dataset(magellan_directory)
self.all_data = magellan.as_array(stitched=False)
```

Full Error:

```
Adding data chunk 41673 of 59904Traceback (most recent call last):

  File "C:\Users\kmarchuk\Documents\GitHub\PyMARIS_Converter\PyMARIS_Converter.py", line 171, in get_working_directory
    self.store_magellan_metadata(magellan_directory_str)

  File "C:\Users\kmarchuk\Documents\GitHub\PyMARIS_Converter\PyMARIS_Converter.py", line 189, in store_magellan_metadata
    self.all_data = magellan.as_array(stitched=False)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 683, in as_array
    blocks = recurse_axes(axes_to_stack_or_stitch, axes_to_slice)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 674, in recurse_axes
    blocks.append(recurse_axes(remaining_loop_axes, valed_axes))

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 674, in recurse_axes
    blocks.append(recurse_axes(remaining_loop_axes, valed_axes))

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 674, in recurse_axes
    blocks.append(recurse_axes(remaining_loop_axes, valed_axes))

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 674, in recurse_axes
    blocks.append(recurse_axes(remaining_loop_axes, valed_axes))

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 602, in recurse_axes
    return self.read_image(**point_axes, memmapped=True)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 819, in read_image
    return res_level.read_image(axes, memmapped)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 252, in read_image
    return reader.read_image(index, memmapped)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\pycromanager\data.py", line 112, in read_image
    np_memmap = np.memmap(self.file, dtype=np.uint8, mode="r")

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\numpy\core\memmap.py", line 267, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)

OSError: [WinError 8] Not enough memory resources are available to process this command
```
I've expanded the page files on my disks, and monitoring the resources, nothing seems amiss. 

This could be an issue with numpy specifically.

Do you know of a way to troubleshoot or work around this error? This seems like a large data error, but my guess is that people are collecting data in the TBs.

Ultimately, this is for my PYMARIS_Converter.

Thanks for your thoughts. 

Kyle

**Comment by henrypinkard** [comment]
Looks like this is running the old code. Try a pip upgrade

**Comment by henrypinkard** [comment]
I just fixed this behavior a couple days ago

**Comment by kdmarchuk** [comment]
I ran a pip upgrade before running this example.

`Successfully installed pycromanager-0.14.2`

Correct version?

**Comment by henrypinkard** [comment]
Oh weird, for some reason `0.14.3` ' build. But I just upgraded it to `0.14.4`, so try again

**Comment by kdmarchuk** [comment]
Wow. That really sped up opening the file with `as_array`

I'm now getting a new error that I previously didn't get 
`Exception: image with keys frozenset({('column', 0), ('row', 0), ('z', 0), ('channel', 0)}) not present in data set`

I'm basically chunking the data into a temporary variable which is then parsed into an Imaris structure with 
`data_temp.write_direct(np.array(all_data[c, z_min - 1]))`

The acquisition started with an empty tile at col=0, row=0. My understanding is that opening the with `as_array` will add zeros into empty positions as I didn't have symmetric data when I did this before. 

Any risk that something happened during the dask speed increase? 

I can test with some demo config data tomorrow if needed. Thanks!

**Comment by henrypinkard** [comment]
> Any risk that something happened during the dask speed increase?

Yes, not only did file reading speed increase, it was hastily coded.

I think I just forgot to add in the empty tile behavior, which is now fixed in the new version

**Comment by kdmarchuk** [comment]
So. Different error. Same place. 


```
  File "C:\Users\kmarchuk\Documents\GitHub\PyMARIS_Converter\PyMARIS_Converter.py", line 107, in run
    data_temp.write_direct(np.array(all_data[c, z_min - 1]))

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\dask\array\core.py", line 1508, in __array__
    x = self.compute()

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\dask\base.py", line 286, in compute
    (result,) = compute(self, traverse=False, **kwargs)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\dask\base.py", line 568, in compute
    results = schedule(dsk, keys, **kwargs)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\dask\threaded.py", line 79, in get
    results = get_async(

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\dask\local.py", line 514, in get_async
    raise_exception(exc, tb)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\dask\local.py", line 325, in reraise
    raise exc

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\dask\local.py", line 223, in execute_task
    result = _execute_task(task, data)

  File "C:\Users\kmarchuk\.conda\envs\pymaris_conv\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed
```

I promise this worked with smaller datasets. Unless there was some other changes made at some point that switched behavior?

Thanks.

**Comment by henrypinkard** [comment]
Yeah I basically rewrote the internals of the whole function for better performance, and seems like there something outside of the test cases I was using that broke.

Is it possible that you could acquire another similar dataset with the demo camera, except with the image size set to something tiny like 16x16 pixels, so that the whole thing is small enough to send to me? Then just send it to me and I'll take a look and figure out where its going wrong/

**Comment by henrypinkard** [comment]
Okay all fixed: https://github.com/micro-manager/pycro-manager/pull/353

I forget to add in the blank tile behavior for the case of non-stitching also

**Comment by kdmarchuk** [comment]
Still the same error at the same point:

`IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed`

The line of code causing the error:
```
all_data = magellan.as_array(stitched=True)
...
data_temp.write_direct(np.array(all_data[c, z_min - 1]))
```

was the way as_array packaged the magellan dataset changed?

**Comment by henrypinkard** [comment]
Okay now its fixed for reeeeeeeal

https://github.com/micro-manager/pycro-manager/pull/354

**Comment by kdmarchuk** [comment]
Just wanted to say that I tested with my large dataset and everything seems to be working.

Thanks!
