### ISSUE TITLE
Possible bug in long duration image acquisition

### ISSUE THREAD

**Issue by carlkesselman** [micro-manager/pycro-manager#588]
### Bug report

**Bug summary**
I am seeing a behavior that looks like a bug.  I'm using a Basler camera with external trigger at 25FPS. Things seem to be working fine for a 30min acquisition.  However, if I do a 60 min acquisition, I'm seeing very funny behavior.  The MM log file shows that all of the requested images are being generated and being written.  However, it appears that the image saving callback is not being called for images at the end of the acquisition. That is if I count the number of times an image_save callback function is called, this is less than the number of images received by micromanager.  This results in the NDTiff files being unreadable, as I think the TIFF files are inconsistent with the index.  I've poked around fairly extensively, and I cannot figure out what would cause this behavior.

Any ideas as to what might be causing this or how to debug this further?

Thanks,

Carl

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Expected outcome**

**Actual outcome**

**Version Info**

  * Operating system:
  * pycromanager version: 
  * MicroManager version:
  * Python version:
  * Python environment (command line, IDE, Jupyter notebook, etc)

**Comment by carlkesselman** [comment]
Hi,

I think the issue is that the micromanager core is receiving the 90000 images I asked for in my acquisition from pycromanager, yet for some reason the pycromanager image_saved_fn is only being called 81596 times. So about 8K acquisitions are not being seen within pycromanager. I think this results in the corrupted file, since as I understand it the images are written by MMCore, while the index is maintained by the pycromanager event callback thread.  It seems that somehow acquisition events are not being passed through, either lost by ZMQ or by micromanager.

Note that this issue only occurs for long acquisitions.  If I use the same framerate, camera, etc. but only do a 40 minute acquisition, everything works reliably.

I have played around with buffers, memory and other things, and so far it has not made a difference.  Perhaps I need to put some more detailed logging into the JavaObject?  Any suggestions as to what I might be looking for?

Carl




On May 3, 2023, at 8:27 AM, Henry Pinkard ***@***.***> wrote:



One thing you can do is try to check if the files are corrupted, or just unreadable during acquisition because the index isn't being updated. Can you open them after the acquisition ends by passing the the path to a new Dataset instance? Are there the correct number of images?

Can you drag them onto a normal TIFF reader to open?

If the former doesnt work, but the latter does, that suggests something wrong with the index. If neihter works that suggests something wrong with the image data. If both work than that suggests something wrong with the callback mechanism

**Comment by henrypinkard** [comment]
> I think this results in the corrupted file, since as I understand it the images are written by MMCore, while the index is maintained by the pycromanager event callback thread.

No, images are not written by MMCore, they are written in the Java layer. This happens prior to the callback thread notifying pycromanager about anything. You may indeed be right about things getting backed up, but its hard to know where to look next without answers to my questions in the previous comment

**Comment by carlkesselman** [comment]
Ahh, ok… perhaps I’m using the wrong term… the java layer is running in the micro-manager process right?

I have tried opening the data files after the fact and the reader hangs on reading the last tif file in the set.

To be clear… everything I’m doing is multithreaded.  I have a separate thread for the acquisition.  The main thread waits around long enough for the acquisition to complete, and it does according to the core log, however, as I mentioned, I don’t get callbacks for about 8K images.  I then exit out of everything.  When I try to open the resulting datasets, I get the hang on the last tiff file.

Does this help?

Carl


On May 3, 2023, at 10:55 AM, Henry Pinkard ***@***.***> wrote:



I think this results in the corrupted file, since as I understand it the images are written by MMCore, while the index is maintained by the pycromanager event callback thread.

No, images are not written by MMCore, they are written in the Java layer. This happens prior to the callback thread notifying pycromanager about anything. You may indeed be right about things getting backed up, but its hard to know where to look next without answers to my questions in the previous comment

**Comment by ieivanov** [comment]
I think I am experience the same or related issue. We started talking about this in #567.

In my acquisition I use the `image_saved_fn` hook to gate the acquisition and only send a new batch of events once the previous batch has finished acquiring / saving. In practice, I see that everything runs well for short acquisitions, but my acquisition slows down significantly for longer runs - i.e. it takes longer and longer to acquire the same set of events.

I am also attributing the slowdown to the `image_saved_fn` hook. As I see it, after a while things start getting backed up, and the function takes longer and longer to execute. @carlkesselman you may see that if you give your acquisition more time it will eventually complete normally. Do I understand correctly that you're currently using the MM core logs to determine when all data should have been acquired?

In my case, once the acquisition starts slowing down I also abort it, but I don't see that the ndtiff datasets are corrupted. My workaround has been to not use a `image_saved_fn` hook and then everything runs smoothly. @carlkesselman if you can, try skipping the image_saved_fn` hook and see if your acquisition will run normally.

**Comment by ieivanov** [comment]
Here is an example demonstrating my acquisition strategy that runs with the demo camera. I am testing now it if shows the same slowdown over time.

```python
from pycromanager import multi_d_acquisition_events, Acquisition
from copy import deepcopy
import time

num_time_points = 500
num_positions = 100

acq_completed = False
last_event_axes = {'position': 0, 'time': 0}

def check_acq_finished(axes, dataset):
    global acq_completed
    if axes == last_event_axes:
        acq_completed = True

acq =  Acquisition(
    directory=r'Q:\Ivan\debug', 
    name='test_acq', 
    image_saved_fn=check_acq_finished,
    show_display=False
)

_events = multi_d_acquisition_events(num_time_points=num_time_points)

for p_idx in range(num_positions):
    t_start = time.time()

    acq_completed = False
    events = deepcopy(_events)
    for event in events:
        event['axes']['position'] = p_idx

    last_event_axes = events[-1]['axes']
    acq.acquire(events)

    # wait for acquisition to finish
    while not acq_completed:
        time.sleep(1)

    print(f'Position {p_idx} acquired in {time.time()-t_start:2.2f} seconds.')
```

**Comment by carlkesselman** [comment]
Thanks.

I’m running without the callback to see what happens.  I’m just using the callback to count the number of frames for status reporting and to detect if there were any hiccups.  I’m trying to think about what would case this to slow down over time… perhaps resources that aren’t released.  The thing that is baffling is that near as I can tell, micromanager is getting all the images, so it’s clearly the hand off from micromanager to micromanager that is dropping stuff on the floor.  The receiving thread is in a loop, so its not thread start up costs.  It is polling from the socket, so perhaps there?

Carl


On May 3, 2023, at 3:35 PM, Ivan Ivanov ***@***.***> wrote:



Here is an example demonstrating my acquisition strategy that runs with the demo camera. I am testing now it if shows the same slowdown over time.

from pycromanager import multi_d_acquisition_events, Acquisition
from copy import deepcopy
import time

num_time_points = 500
num_positions = 100

acq_completed = False
last_event_axes = {'position': 0, 'time': 0}

def check_acq_finished(axes, dataset):
    global acq_completed
    if axes == last_event_axes:
        acq_completed = True

acq =  Acquisition(
    directory=r'Q:\Ivan\debug',
    name='test_acq',
    image_saved_fn=check_acq_finished,
    show_display=False
)

_events = multi_d_acquisition_events(num_time_points=num_time_points)

for p_idx in range(num_positions):
    t_start = time.time()

    acq_completed = False
    events = deepcopy(_events)
    for event in events:
        event['axes']['position'] = p_idx

    last_event_axes = events[-1]['axes']
    acq.acquire(events)

    # wait for acquisition to finish
    while not acq_completed:
        time.sleep(1)

    print(f'Position {p_idx} acquired in {time.time()-t_start:2.2f} seconds.')

**Comment by carlkesselman** [comment]
Actually, this should make any difference as there the pycromanager image_saved thread is still called to update the index entry.

In any case, I’m running now without user provided function to see if it makes a difference.

Carl


On May 3, 2023, at 3:45 PM, Carl Kesselman ***@***.***> wrote:

Thanks.

I’m running without the callback to see what happens.  I’m just using the callback to count the number of frames for status reporting and to detect if there were any hiccups.  I’m trying to think about what would case this to slow down over time… perhaps resources that aren’t released.  The thing that is baffling is that near as I can tell, micromanager is getting all the images, so it’s clearly the hand off from micromanager to micromanager that is dropping stuff on the floor.  The receiving thread is in a loop, so its not thread start up costs.  It is polling from the socket, so perhaps there?

Carl


On May 3, 2023, at 3:35 PM, Ivan Ivanov ***@***.***> wrote:



Here is an example demonstrating my acquisition strategy that runs with the demo camera. I am testing now it if shows the same slowdown over time.

from pycromanager import multi_d_acquisition_events, Acquisition
from copy import deepcopy
import time

num_time_points = 500
num_positions = 100

acq_completed = False
last_event_axes = {'position': 0, 'time': 0}

def check_acq_finished(axes, dataset):
    global acq_completed
    if axes == last_event_axes:
        acq_completed = True

acq =  Acquisition(
    directory=r'Q:\Ivan\debug',
    name='test_acq',
    image_saved_fn=check_acq_finished,
    show_display=False
)

_events = multi_d_acquisition_events(num_time_points=num_time_points)

for p_idx in range(num_positions):
    t_start = time.time()

    acq_completed = False
    events = deepcopy(_events)
    for event in events:
        event['axes']['position'] = p_idx

    last_event_axes = events[-1]['axes']
    acq.acquire(events)

    # wait for acquisition to finish
    while not acq_completed:
        time.sleep(1)

    print(f'Position {p_idx} acquired in {time.time()-t_start:2.2f} seconds.')

**Comment by carlkesselman** [comment]
Ok.

I’ve run with both callbacks on and off.

Here is what I’ve learned:

1) I was wrong about the file being corrupted.  Its fine. It just takes a long time to load, and I didn’t wait long enough.
2) The file has all of the events I expected in it.
3) The number of times that the image_storage_fn callback is called is definitely not equal to the number of the images in the file. So my original observation that callback events are being lost somewhere remains true.

Any ideas?

Thanks,

Carl


On May 3, 2023, at 4:37 PM, Carl Kesselman ***@***.***> wrote:

Actually, this should make any difference as there the pycromanager image_saved thread is still called to update the index entry.

In any case, I’m running now without user provided function to see if it makes a difference.

Carl


On May 3, 2023, at 3:45 PM, Carl Kesselman ***@***.***> wrote:

Thanks.

I’m running without the callback to see what happens.  I’m just using the callback to count the number of frames for status reporting and to detect if there were any hiccups.  I’m trying to think about what would case this to slow down over time… perhaps resources that aren’t released.  The thing that is baffling is that near as I can tell, micromanager is getting all the images, so it’s clearly the hand off from micromanager to micromanager that is dropping stuff on the floor.  The receiving thread is in a loop, so its not thread start up costs.  It is polling from the socket, so perhaps there?

Carl


On May 3, 2023, at 3:35 PM, Ivan Ivanov ***@***.***> wrote:



Here is an example demonstrating my acquisition strategy that runs with the demo camera. I am testing now it if shows the same slowdown over time.

from pycromanager import multi_d_acquisition_events, Acquisition
from copy import deepcopy
import time

num_time_points = 500
num_positions = 100

acq_completed = False
last_event_axes = {'position': 0, 'time': 0}

def check_acq_finished(axes, dataset):
    global acq_completed
    if axes == last_event_axes:
        acq_completed = True

acq =  Acquisition(
    directory=r'Q:\Ivan\debug',
    name='test_acq',
    image_saved_fn=check_acq_finished,
    show_display=False
)

_events = multi_d_acquisition_events(num_time_points=num_time_points)

for p_idx in range(num_positions):
    t_start = time.time()

    acq_completed = False
    events = deepcopy(_events)
    for event in events:
        event['axes']['position'] = p_idx

    last_event_axes = events[-1]['axes']
    acq.acquire(events)

    # wait for acquisition to finish
    while not acq_completed:
        time.sleep(1)

    print(f'Position {p_idx} acquired in {time.time()-t_start:2.2f} seconds.')

**Comment by henrypinkard** [comment]
> The thing that is baffling is that near as I can tell, micromanager is getting all the images, so it’s clearly the hand off from micromanager to micromanager that is dropping stuff on the floor. The receiving thread is in a loop, so its not thread start up costs. It is polling from the socket, so perhaps there?

The [socket that pushes out updates](https://github.com/micro-manager/pycro-manager/blob/main/java/src/main/java/org/micromanager/remote/RemoteStorageMonitor.java) that images are saved runs in a dedicated thread, as does the one that receives the updates on the python side.

The [handoff from saving to this thread](https://github.com/micro-manager/NDTiffStorage/blob/d7645a418013017e49a2d38f89cf8b486e20468b/java/src/main/java/org/micromanager/ndtiffstorage/NDTiffStorage.java#L826) doesn't have any obvious problems.

If the image saved callback isn't firing as many times as it should, is it because it is skipping images? Or does it get behind and never catch up? I think its conceivable that the pulling on the python side is not fast enough to keep up with the pushing, in which case notifications of new images might be dropped. This should be easily testable by just printing the `axes` of each image that has arrived.

**Comment by carlkesselman** [comment]
I checked this. What seems to be happening is that the events at the end of the acquisition are being lost.  The time sequence up to that the end is complete.


Carl


On May 4, 2023, at 12:06 PM, Henry Pinkard ***@***.***> wrote:



The thing that is baffling is that near as I can tell, micromanager is getting all the images, so it’s clearly the hand off from micromanager to micromanager that is dropping stuff on the floor. The receiving thread is in a loop, so its not thread start up costs. It is polling from the socket, so perhaps there?

The socket that pushes out updates<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_blob_main_java_src_main_java_org_micromanager_remote_RemoteStorageMonitor.java&d=DwMFaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=_JUdS50rjTi_1C3HIKahosDYoTcNe0aF5n9ZqFJva9jstofVs2nzVMC-EsGtEJl5&s=F-lEm5gqF-vqF44JP9FMDlDSHW3usC5aUMxP_xQV0tA&e=> that images are saved runs in a dedicated thread, as does the one that receives the updates on the python side.

The handoff from saving to this thread<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_NDTiffStorage_blob_d7645a418013017e49a2d38f89cf8b486e20468b_java_src_main_java_org_micromanager_ndtiffstorage_NDTiffStorage.java-23L826&d=DwMFaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=_JUdS50rjTi_1C3HIKahosDYoTcNe0aF5n9ZqFJva9jstofVs2nzVMC-EsGtEJl5&s=laki84pqUexPdCFBiSkGwgSX0YNUu21f2GWF59nFc6Q&e=> doesn't have any obvious problems.

If the image saved callback isn't firing as many times as it should, is it because it is skipping images? Or does it get behind and never catch up? I think its conceivable that the pulling on the python side is not fast enough to keep up with the pushing, in which case notifications of new images might be dropped. This should be easily testable by just printing the axes of each image that has arrived.

**Comment by henrypinkard** [comment]
Okay thanks for checking. That to me suggests things are getting backed up and then truncated early when the acquisition ends. I can look into this some more, but I also wonder what the behavior _should_ be when these callbacks aren't able to keep up. Any thoughts @ieivanov ?

**Comment by carlkesselman** [comment]
So I’m assuming that the reason why this kicks in so late is that stuff is being buffered up until a point and then collapse.

This is running on the very latest version of python, on a pretty beefy windows 10 machine.  I”m basically just counting frames in the callback, nothing fancy, so one wonders is python threading might be part of the culprit here and that this has been there all along, but it just shows up because of the length of the acquisition I’m doing.

Thanks,

Carl


On May 4, 2023, at 4:24 PM, Henry Pinkard ***@***.***> wrote:



Okay thanks for checking. That to me suggests things are getting backed up and then truncated early when the acquisition ends. I can look into this some more, but I also wonder what the behavior should be when these callbacks aren't able to keep up. Any thoughts @ieivanov<https://urldefense.us/v2/url?u=https-3A__github.com_ieivanov&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=kF_d97Tdn5mSf2Y3lTu1DkKAkHGx42COMgyxKyOMNA0YnJs4cV5GU3czaPMWvX2H&s=5Xcb6ihZkV59yk0uXeqDP_D3ZFfwlMs1lV9U-SBWjUA&e=> ?

**Comment by henrypinkard** [comment]
I dug into this and it seems there was a bug where there was a missing synchronization, in which the python side signaled to the java side that it has received all the information about the dataset currently being acquired and it was safe to shut down. That should now be fixed by changes in MM/PM and NDTiff. I tested this usign the following:
```python
from pycromanager import multi_d_acquisition_events, Acquisition

num_time_points = 10000

def check_acq_finished(axes, dataset):
    print(axes)

with Acquisition(directory='/Users/henrypinkard/tmp/', name='test_acq', image_saved_fn=check_acq_finished, show_display=True) as acq:
    _events = multi_d_acquisition_events(num_time_points=num_time_points)
    acq.acquire(_events)
```


I set a breakpoint in in the callback function, waited for the acq to finish and then released the breakpoint, thus suimulating a callback function that wasn't able to keep up. Once releasing, all the images were able to be received.

This still might not explain/solve slowdowns in the function over long acquisitions, so I'd be curious to know from the two of you how this performs nwo that the correct behavior is implemented. Based on my computer, it seems sending these signals is super fast, so I would be confused by they would get backed up unless youre doing heavy processing in the image callback function.

Thanks to both of you for digging this up!

https://github.com/micro-manager/pycro-manager/pull/592
https://github.com/micro-manager/NDTiffStorage/pull/111

**Comment by carlkesselman** [comment]
Wonderful, thanks.

I’ll update and rerun my test and see what happens.


Thanks for hunting this down!  I would have never found this.

Carl


On May 5, 2023, at 11:46 AM, Henry Pinkard ***@***.***> wrote:



I dug into this and it seems there was a bug where there was a missing synchronization, in which the python side signaled to the java side that it has received all the information about the dataset currently being acquired and it was safe to shut down. That should now be fixed by changes in MM/PM and NDTiff. I tested this usign the following:

from pycromanager import multi_d_acquisition_events, Acquisition

num_time_points = 10000

def check_acq_finished(axes, dataset):
    print(axes)

with Acquisition(directory='/Users/henrypinkard/tmp/', name='test_acq', image_saved_fn=check_acq_finished, show_display=True) as acq:
    _events = multi_d_acquisition_events(num_time_points=num_time_points)
    acq.acquire(_events)

I set a breakpoint in in the callback function, waited for the acq to finish and then released the breakpoint, thus suimulating a callback function that wasn't able to keep up. Once releasing, all the images were able to be received.

This still might not explain/solve slowdowns in the function over long acquisitions, so I'd be curious to know from the two of you how this performs nwo that the correct behavior is implemented. Based on my computer, it seems sending these signals is super fast, so I would be confused by they would get backed up unless youre doing heavy processing in the image callback function.

Thanks to both of you for digging this up!

#592<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_pull_592&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=GZY-1uqjQWGsw1oLJuyHzYiP-W-jwROKpQDVVzNv-hucUALC8-aIxOu-3ow8Hgf3&s=g08oDEL6ZbHTy53b9KLYK7dnWTWKvToBIfEref4v6yQ&e=>
micro-manager/NDTiffStorage#111<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_NDTiffStorage_pull_111&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=GZY-1uqjQWGsw1oLJuyHzYiP-W-jwROKpQDVVzNv-hucUALC8-aIxOu-3ow8Hgf3&s=x70bY3aVjwR8rzo5yh5bQgz6GZZ42BiOuERPjgfw7gs&e=>

**Comment by dpshepherd** [comment]
Potentially related, or maybe not - 

We've had a couple long, hardware-triggered acquisitions using pycromanager fail recently due to the circular buffer overflowing after a few thousand images. This is writing to an 16.0 TB NVME raid 0 PCIe4.0 setup capable of >20 GB/s sustained.

The instrument is really tied up at the moment, so haven't had a chance to troubleshoot. We just increased the circular buffer to a really large side to make sure we don't get the error.

**Comment by carlkesselman** [comment]
I may have seen this as well but could not reproduce reliably yet.

Carl

Sent from my iPhone

On May 5, 2023, at 1:01 PM, Doug Shepherd ***@***.***> wrote:

﻿

Potentially related, or maybe not -

We've had a couple long, hardware-triggered acquisitions using pycromanager fail recently due to the circular buffer overflowing after a few thousand images. This is writing to an 16.0 TB NVME raid 0 PCIe4.0 setup capable of >20 GB/s sustained.

The instrument is really tied up at the moment, so haven't had a chance to troubleshoot. We just increased the circular buffer to a really large side to make sure we don't get the error.

**Comment by henrypinkard** [comment]
I would be surprised if this related since this mechanism should be totally asynchronous to saving.

FYI this [script for running speed tests with NDTiff](https://github.com/micro-manager/pycro-manager/blob/main/scripts/speed_test.py)

And [this notebook for analyzing results](https://github.com/henrypinkard/micro-manager/blob/main/acqengj_speed_test/analysis.ipynb) may be helpful

**Comment by carlkesselman** [comment]
Sorry, but are these pushed to conda, or should I clone and install.

Carl


On May 5, 2023, at 11:54 AM, Carl Kesselman ***@***.***> wrote:

Wonderful, thanks.

I’ll update and rerun my test and see what happens.


Thanks for hunting this down!  I would have never found this.

Carl


On May 5, 2023, at 11:46 AM, Henry Pinkard ***@***.***> wrote:



I dug into this and it seems there was a bug where there was a missing synchronization, in which the python side signaled to the java side that it has received all the information about the dataset currently being acquired and it was safe to shut down. That should now be fixed by changes in MM/PM and NDTiff. I tested this usign the following:

from pycromanager import multi_d_acquisition_events, Acquisition

num_time_points = 10000

def check_acq_finished(axes, dataset):
    print(axes)

with Acquisition(directory='/Users/henrypinkard/tmp/', name='test_acq', image_saved_fn=check_acq_finished, show_display=True) as acq:
    _events = multi_d_acquisition_events(num_time_points=num_time_points)
    acq.acquire(_events)

I set a breakpoint in in the callback function, waited for the acq to finish and then released the breakpoint, thus suimulating a callback function that wasn't able to keep up. Once releasing, all the images were able to be received.

This still might not explain/solve slowdowns in the function over long acquisitions, so I'd be curious to know from the two of you how this performs nwo that the correct behavior is implemented. Based on my computer, it seems sending these signals is super fast, so I would be confused by they would get backed up unless youre doing heavy processing in the image callback function.

Thanks to both of you for digging this up!

#592<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_pull_592&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=GZY-1uqjQWGsw1oLJuyHzYiP-W-jwROKpQDVVzNv-hucUALC8-aIxOu-3ow8Hgf3&s=g08oDEL6ZbHTy53b9KLYK7dnWTWKvToBIfEref4v6yQ&e=>
micro-manager/NDTiffStorage#111<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_NDTiffStorage_pull_111&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=GZY-1uqjQWGsw1oLJuyHzYiP-W-jwROKpQDVVzNv-hucUALC8-aIxOu-3ow8Hgf3&s=x70bY3aVjwR8rzo5yh5bQgz6GZZ42BiOuERPjgfw7gs&e=>

**Comment by henrypinkard** [comment]
just went through to pip/nightly build. Conda takes a bit longer.

Theres still something strange going on with the automated tests though--they work on my laptop but not on github actions. So let me know if you see anything strange

**Comment by henrypinkard** [comment]
Now fixed by https://github.com/micro-manager/pycro-manager/pull/596

So I expect everything should work now, but there is still the question of if these image callback functions get backed up. Even if they do, they should all arrive eventually. This can be tested by comparing the rate of their arrival times in the callback function to the frame rate at which the camera is running. Closing for now, let me know if you all run into anything else related

**Comment by ieivanov** [comment]
Hey guys, thanks for looking into this. I'm away until the end of the month, I'll take another look when I get back.

**Comment by carlkesselman** [comment]
Is there perhaps something not right.  Got latest nightly build of MM, but seeing the following when trying to test this:

2023-05-10T06:26:46.255430 tid49792 [dbg,Core] Will set camera BaslerCamera exposure to 10.000 ms
06:26:46 MainThread Acquire 250 events from tail camera
2023-05-10T06:26:46.257307 tid49792 [dbg,Core] Did set camera BaslerCamera exposure to 10.000 ms
2023-05-10T06:26:46.407142 tid19696 [IFO,App] Image queue size: 0
2023-05-10T06:26:46.407160 tid19696 [IFO,App] waiting for image to save
Exception in thread tail camera:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\spim-data\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\spim-data\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\carl\Repos\spim-data\spimmgr\mmacquisition.py", line 90, in _acquire_loop
    with pycromanager.Acquisition(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\spim-data\Lib\site-packages\pycromanager\acquisitions.py", line 349, in __init__
    self._remote_storage_monitor = JavaObject('org.micromanager.remote.RemoteStorageMonitor', port=self._port)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\spim-data\Lib\site-packages\pycromanager\zmq_bridge\wrappers.py", line 74, in __new__
    return bridge._construct_java_object(classpath, new_socket=new_socket, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\spim-data\Lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 379, in _construct_java_object
    valid_method_spec, deserialize_types = _check_method_args(methods_with_name, args)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\spim-data\Lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 853, in _check_method_args
    raise Exception(
Exception: Incorrect arguments.
Expected org.micromanager.ndtiffstorage.NDTiffStorage


On May 8, 2023, at 9:04 PM, Henry Pinkard ***@***.***> wrote:



Closed #588<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_issues_588&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=wp2YHGh-6AqnImy5BoVTLoDbvHN0Ff_74RBf3CuBisn3JKg1WRrPRMX8g4fCWXiA&s=b8uCCjDBYqhXRwhrlJCxIpDbI_i-IT1QEQtIbqRwzVU&e=> as completed.

**Comment by carlkesselman** [comment]
I am still seeing a difference in the number of images stored in the NDTiff files and the number of image-store callbacks.  Call back is doing almost nothing.  Pycromanger version is 27.5
Micromanager is the May 9th, nightly build.

If you tell me where to look, I can try to debug further.

Carl



On May 10, 2023, at 5:39 PM, Carl Kesselman ***@***.***> wrote:

That seems to have fixed it…. Not quite sure how that happened.

Carl


On May 10, 2023, at 5:23 PM, Henry Pinkard ***@***.***> wrote:



You must be somehow running an older version of PycroManagerJava. The current version is 0.39.2, and this is what's currently shipping with MM<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_micro-2Dmanager_blob_7bc4084a592e17c73060aada6e1a13b6b1581bef_buildscripts_ivy.xml-23L55&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=md6ghP7e1qDlM_4x6MqCFkSd_Qw4RBMosSKfEBdpz1GLzYvvmtWB_9ksMjFd8gT4&s=dtr74QCwaT-Yk_yuu3OjsJwvfheYgc9kasbxAS85gRE&e=>. Maybe try deleting nightly build and reinstalling from scratch?

**Comment by henrypinkard** [comment]
This script works as expected for me with demo config:

```python
from pycromanager import multi_d_acquisition_events, Acquisition

num_time_points = 10000

def check_acq_finished(axes, dataset):
    print(axes)

with Acquisition(directory='/Users/henrypinkard/tmp/', name='test_acq', image_saved_fn=check_acq_finished, show_display=True) as acq:
    _events = multi_d_acquisition_events(num_time_points=num_time_points)
    acq.acquire(_events)
```

I set a breakpoint at the `print(axes)` and wait for the entire acquisition to run before running any callbacks. (you could similarly put a long `time.sleep` there).

Does this work for you? Are you still getting the first few thousand callbacks but not later ones? does it depend on the number of images or the speed at which they are acquired?

**Comment by ieivanov** [comment]
I just reran the code I posted [above](https://github.com/micro-manager/pycro-manager/issues/588#issuecomment-1533839159) with the latest MM/PM, changing the sleep time from 1 s to 0.01 s. The first time point finishes acquiring in 6 seconds, and now the last one finished in about 10.5 seconds. So things have gotten better than before (the last time point used to take 18 s), but there may still be a slowdown over time. Is there a simple way to test if this is a general python issue (launching threads, etc) versus an issue with the pycromanager code?

**Comment by carlkesselman** [comment]
I’ll try to look and see.  I’ve been swamped the last couple of weeks.

Carl


On Jun 1, 2023, at 3:27 PM, Ivan Ivanov ***@***.***> wrote:



I just reran the code I posted above<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_pycro-2Dmanager_issues_588-23issuecomment-2D1533839159&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=1SxI0bu2Ms0DjwaixT8rqJzpYSsvH37mUH43bnKdRyG5NMDHvT86z_yEHjV6AxmZ&s=bChAwFa02y93sCLp1-2lRx_MmIeV1kMhkgi_c9xrZqs&e=> with the latest MM/PM, changing the sleep time from 1 s to 0.01 s. The first time point finishes acquiring in 6 seconds, and now the last one finished in about 10.5 seconds. So things have gotten better than before (the last time point used to take 18 s), but there may still be a slowdown over time. Is there a simple way to test if this is a general python issue (launching threads, etc) versus an issue with the pycromanager code?

**Comment by ieivanov** [comment]
Thanks Carl. To clarify a bit, in my experience the `image_saved_fn` executes the right number of times - 500 * 100,  which is probably smaller than in your tests, but it takes longer to execute with each iteration. I think the two issues are likely related.

**Comment by carlkesselman** [comment]
Yea… it would seem to be so.   I can keep up until a certain point and then things go south.  So it seems that the big question is why is the time per iteration increasing.

Carl


On Jun 1, 2023, at 3:32 PM, Ivan Ivanov ***@***.***> wrote:



Thanks Carl. To clarify a bit, in my experience the image_saved_fn executes the right number of times - 500 * 100, which is probably smaller than in your tests, but it takes longer to execute with each iteration. I think the two issues are likely related.

**Comment by henrypinkard** [comment]
Ok I'm now seeing this too with Ivan's code

It looks to me like one of the internal queues gets filled up and then things start backing up. I'll investigate further


```
Position 0 acquired in 6.03 seconds.
Position 1 acquired in 6.05 seconds.
Position 2 acquired in 6.04 seconds.
Position 3 acquired in 6.05 seconds.
Position 4 acquired in 6.06 seconds.
Position 5 acquired in 6.06 seconds.
Position 6 acquired in 6.05 seconds.
Position 7 acquired in 6.05 seconds.
Position 8 acquired in 6.06 seconds.
Position 9 acquired in 6.06 seconds.
Position 10 acquired in 6.05 seconds.
Position 11 acquired in 6.05 seconds.
Position 12 acquired in 6.05 seconds.
Position 13 acquired in 6.05 seconds.
Position 14 acquired in 6.11 seconds.
Position 15 acquired in 6.06 seconds.
Position 16 acquired in 6.05 seconds.
Position 17 acquired in 6.05 seconds.
Position 18 acquired in 6.05 seconds.
Position 19 acquired in 6.07 seconds.
Position 20 acquired in 6.05 seconds.
Position 21 acquired in 6.05 seconds.
Position 22 acquired in 6.05 seconds.
Position 23 acquired in 6.05 seconds.
Position 24 acquired in 6.05 seconds.
Position 25 acquired in 6.05 seconds.
Position 26 acquired in 6.07 seconds.
Position 27 acquired in 6.07 seconds.
Position 28 acquired in 6.05 seconds.
Position 29 acquired in 6.05 seconds.
Position 30 acquired in 6.06 seconds.
Position 31 acquired in 6.06 seconds.
Position 32 acquired in 6.06 seconds.
Position 33 acquired in 6.05 seconds.
Position 34 acquired in 6.07 seconds.
Position 35 acquired in 6.05 seconds.
Position 36 acquired in 6.04 seconds.
Position 37 acquired in 6.06 seconds.
Position 38 acquired in 6.06 seconds.
Position 39 acquired in 6.05 seconds.
Position 40 acquired in 6.06 seconds.
Position 41 acquired in 6.06 seconds.
Position 42 acquired in 6.08 seconds.
Position 43 acquired in 9.08 seconds.
Position 44 acquired in 6.05 seconds.
Position 45 acquired in 6.06 seconds.
Position 46 acquired in 6.07 seconds.
Position 47 acquired in 6.05 seconds.
Position 48 acquired in 6.07 seconds.
Position 49 acquired in 6.07 seconds.
Position 50 acquired in 6.08 seconds.
Position 51 acquired in 6.05 seconds.
Position 52 acquired in 6.05 seconds.
Position 53 acquired in 6.07 seconds.
Position 54 acquired in 6.07 seconds.
Position 55 acquired in 6.07 seconds.
Position 56 acquired in 6.07 seconds.
Position 57 acquired in 6.06 seconds.
Position 58 acquired in 6.07 seconds.
Position 59 acquired in 6.07 seconds.
Position 60 acquired in 6.08 seconds.
Position 61 acquired in 6.09 seconds.
Position 62 acquired in 6.08 seconds.
Position 63 acquired in 6.09 seconds.
Position 64 acquired in 6.09 seconds.
Position 65 acquired in 6.09 seconds.
Position 66 acquired in 6.10 seconds.
Position 67 acquired in 6.09 seconds.
Position 68 acquired in 6.10 seconds.
Position 69 acquired in 6.08 seconds.
Position 70 acquired in 7.08 seconds.
Position 71 acquired in 7.10 seconds.
Position 72 acquired in 7.10 seconds.
Position 73 acquired in 7.09 seconds.
Position 74 acquired in 7.10 seconds.
Position 75 acquired in 7.10 seconds.
Position 76 acquired in 7.10 seconds.
Position 77 acquired in 7.08 seconds.
Position 78 acquired in 7.10 seconds.
Position 79 acquired in 7.09 seconds.
Position 80 acquired in 7.09 seconds.
Position 81 acquired in 7.08 seconds.
Position 82 acquired in 8.09 seconds.
Position 83 acquired in 8.10 seconds.
Position 84 acquired in 8.10 seconds.
Position 85 acquired in 8.10 seconds.
Position 86 acquired in 8.09 seconds.
Position 87 acquired in 8.12 seconds.
Position 88 acquired in 8.11 seconds.
Position 89 acquired in 8.12 seconds.

```

**Comment by carlkesselman** [comment]
Cool.  I think this is consistent with what I’ve been seeing.

Carl


On Jun 2, 2023, at 8:56 AM, Henry Pinkard ***@***.***> wrote:



Ok I'm now seeing this too with Ivan's code

It looks to me like one of the internal queues gets filled up and then things start backing up. I'll investigate further

Position 0 acquired in 6.03 seconds.
Position 1 acquired in 6.05 seconds.
Position 2 acquired in 6.04 seconds.
Position 3 acquired in 6.05 seconds.
Position 4 acquired in 6.06 seconds.
Position 5 acquired in 6.06 seconds.
Position 6 acquired in 6.05 seconds.
Position 7 acquired in 6.05 seconds.
Position 8 acquired in 6.06 seconds.
Position 9 acquired in 6.06 seconds.
Position 10 acquired in 6.05 seconds.
Position 11 acquired in 6.05 seconds.
Position 12 acquired in 6.05 seconds.
Position 13 acquired in 6.05 seconds.
Position 14 acquired in 6.11 seconds.
Position 15 acquired in 6.06 seconds.
Position 16 acquired in 6.05 seconds.
Position 17 acquired in 6.05 seconds.
Position 18 acquired in 6.05 seconds.
Position 19 acquired in 6.07 seconds.
Position 20 acquired in 6.05 seconds.
Position 21 acquired in 6.05 seconds.
Position 22 acquired in 6.05 seconds.
Position 23 acquired in 6.05 seconds.
Position 24 acquired in 6.05 seconds.
Position 25 acquired in 6.05 seconds.
Position 26 acquired in 6.07 seconds.
Position 27 acquired in 6.07 seconds.
Position 28 acquired in 6.05 seconds.
Position 29 acquired in 6.05 seconds.
Position 30 acquired in 6.06 seconds.
Position 31 acquired in 6.06 seconds.
Position 32 acquired in 6.06 seconds.
Position 33 acquired in 6.05 seconds.
Position 34 acquired in 6.07 seconds.
Position 35 acquired in 6.05 seconds.
Position 36 acquired in 6.04 seconds.
Position 37 acquired in 6.06 seconds.
Position 38 acquired in 6.06 seconds.
Position 39 acquired in 6.05 seconds.
Position 40 acquired in 6.06 seconds.
Position 41 acquired in 6.06 seconds.
Position 42 acquired in 6.08 seconds.
Position 43 acquired in 9.08 seconds.
Position 44 acquired in 6.05 seconds.
Position 45 acquired in 6.06 seconds.
Position 46 acquired in 6.07 seconds.
Position 47 acquired in 6.05 seconds.
Position 48 acquired in 6.07 seconds.
Position 49 acquired in 6.07 seconds.
Position 50 acquired in 6.08 seconds.
Position 51 acquired in 6.05 seconds.
Position 52 acquired in 6.05 seconds.
Position 53 acquired in 6.07 seconds.
Position 54 acquired in 6.07 seconds.
Position 55 acquired in 6.07 seconds.
Position 56 acquired in 6.07 seconds.
Position 57 acquired in 6.06 seconds.
Position 58 acquired in 6.07 seconds.
Position 59 acquired in 6.07 seconds.
Position 60 acquired in 6.08 seconds.
Position 61 acquired in 6.09 seconds.
Position 62 acquired in 6.08 seconds.
Position 63 acquired in 6.09 seconds.
Position 64 acquired in 6.09 seconds.
Position 65 acquired in 6.09 seconds.
Position 66 acquired in 6.10 seconds.
Position 67 acquired in 6.09 seconds.
Position 68 acquired in 6.10 seconds.
Position 69 acquired in 6.08 seconds.
Position 70 acquired in 7.08 seconds.
Position 71 acquired in 7.10 seconds.
Position 72 acquired in 7.10 seconds.
Position 73 acquired in 7.09 seconds.
Position 74 acquired in 7.10 seconds.
Position 75 acquired in 7.10 seconds.
Position 76 acquired in 7.10 seconds.
Position 77 acquired in 7.08 seconds.
Position 78 acquired in 7.10 seconds.
Position 79 acquired in 7.09 seconds.
Position 80 acquired in 7.09 seconds.
Position 81 acquired in 7.08 seconds.
Position 82 acquired in 8.09 seconds.
Position 83 acquired in 8.10 seconds.
Position 84 acquired in 8.10 seconds.
Position 85 acquired in 8.10 seconds.
Position 86 acquired in 8.09 seconds.
Position 87 acquired in 8.12 seconds.
Position 88 acquired in 8.11 seconds.
Position 89 acquired in 8.12 seconds.

**Comment by henrypinkard** [comment]
Ok I think I found it. When sending the info about the image that was just saved to the `Dataset` class, it was parsing the full index every time to update its state, when all that was needed was to just parse the info for the new image. Fixed by: https://github.com/micro-manager/NDTiffStorage/pull/118, so a pip upgrade to ndtiff 2.0.1 should do the trick.

**Comment by henrypinkard** [comment]
@ieivanov I think you had mentioned a while back that the napari viewer was slower than NDViewer over long acquisitions. I wonder if this now fixes that

**Comment by carlkesselman** [comment]
Ok… I was able to do an hour long acquisition without dropping a frame. Running a more challenging test case now, but I think you got it.

It would make sense that this error would also compound my multicamera acqusision and explains why the multithreaded version didn’t work any better due to the GIL and the increasing time spent in the handler thread.

Tranks a lot for tracking this down!  I’m actually a little surprised no one else saw this.

Carl


On Jun 2, 2023, at 5:18 PM, Henry Pinkard ***@***.***> wrote:



Ok I think I found it. When sending the info about the image that was just saved to the Dataset class, it was parsing the full index every time to update its state, when all that was needed was to just parse the info for the new image. Fixed by: micro-manager/NDTiffStorage#118<https://urldefense.us/v2/url?u=https-3A__github.com_micro-2Dmanager_NDTiffStorage_pull_118&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=Faii0AlMrf1k7iyg1jwywdMUm-HoWdrmnNXT-JZzGgeJx6_tRIDJ-azxyxQ9Y25s&s=fJck3-NNCOOKw4wZ4op-kwJBFjhLJ6CnmQLzv7wtEQU&e=>, so a pip upgrade to ndtiff 2.0.1 should do the trick.

**Comment by henrypinkard** [comment]
Great! Thanks for the help in diagnosing it

**Comment by ieivanov** [comment]
That's it, this fixed the problem! Now all positions in my test complete in under 6 seconds. Thanks a bunch Henry!

**Comment by carlkesselman** [comment]
Just did an hour long run, three cameras…. No dropped frames, rock solid.

I think we are there!

Carl


On Jun 5, 2023, at 11:28 AM, Henry Pinkard ***@***.***> wrote:



Great! Thanks for the help in diagnosing it

**Comment by henrypinkard** [comment]
Awesome!

**Comment by henrypinkard** [comment]
On thing that just occurred to me: it seems like this setup using multiple cores is something people repeatedly ask about. If either of you have the time or interest, it would be a nice addition to the [Applications](https://pycro-manager.readthedocs.io/en/latest/applications.html) page on the docs showing a simple demo camera way of setting thing up

**Comment by carlkesselman** [comment]
Be happy too. I also need to do a PR on my multi camera basler driver

Carl

Sent from my iPhone

On Jun 6, 2023, at 1:02 PM, Henry Pinkard ***@***.***> wrote:

﻿

On thing that just occurred to me: it seems like this setup using multiple cores is something people repeatedly ask about. If either of you have the time or interest, it would be a nice addition to the Applications<https://urldefense.us/v2/url?u=https-3A__pycro-2Dmanager.readthedocs.io_en_latest_applications.html&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=_m7Puamaiea3pprfB8S0yoskR23Ki1Y_39whJSj2W8HhiECt-gZceh5dYLA_sYE3&s=AqkvNWEdJinOAavou8FcD8EYWMyKbPA4zEQdz3CEC1M&e=> page on the docs showing a simple demo camera way of setting thing up

**Comment by carlkesselman** [comment]
FYI… just found another problem  and posted a new issue.  This probably should be in NDTiff, as I hunted it down and found it.

Carl


On Jun 6, 2023, at 10:02 AM, Henry Pinkard ***@***.***> wrote:



On thing that just occurred to me: it seems like this setup using multiple cores is something people repeatedly ask about. If either of you have the time or interest, it would be a nice addition to the Applications<https://urldefense.us/v2/url?u=https-3A__pycro-2Dmanager.readthedocs.io_en_latest_applications.html&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=sGCma2ufaUVT-N141kRIZQ&m=_m7Puamaiea3pprfB8S0yoskR23Ki1Y_39whJSj2W8HhiECt-gZceh5dYLA_sYE3&s=AqkvNWEdJinOAavou8FcD8EYWMyKbPA4zEQdz3CEC1M&e=> page on the docs showing a simple demo camera way of setting thing up
