### ISSUE TITLE
Exception thrown after acquisition completes

### ISSUE THREAD

**Issue by ckolluru** [micro-manager/pycro-manager#604]
I have the latest build of pycromanager (0.27.5)

With the minimal working example of pycro-manager below and the demo config of MM, the acquisition runs without errors.

```
from pycromanager import Acquisition, multi_d_acquisition_events

with Acquisition(directory='/path/to/saving/dir', name='acquisition_name') as acq:
    # Generate the events for a single z-stack
    events = multi_d_acquisition_events(z_start=0, z_end=10, z_step=0.5)
    acq.acquire(events)
```

However, when I'm implementing my workflow, the acquisition runs fine but ends with this exception. 
```
Exception ignored in: <function _JavaObjectShadow.__del__ at 0x000001F7FAC2D080>
Traceback (most recent call last):
  File "C:\Users\cxk340\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 644, 
in __del__
  File "C:\Users\cxk340\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 568, 
in _close
  File "C:\Users\cxk340\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 582, 
in _send
  File "C:\Users\cxk340\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 330, 
in _send
  File "C:\Users\cxk340\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 122, 
in send
  File "C:\Users\cxk340\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\zmq\sugar\socket.py", line 735, in send_multipart
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

I get the same error with a minimal version of my code and the demo configuration as well.
To replicate this, open MM with the demo config file and just add one position to the position list using the Mark button.

```
import numpy as np
import time
from pycromanager import Acquisition, Studio, multi_d_acquisition_events, Core
import os

class acquisition():
    def __init__(self):
        self.core = None

        self.NUM_TILES = 1
        self.PIXEL_SIZE = 0
        self.STORAGE_DIRECTORY = None
        self.TILE_SIZE_X = None
        self.TILE_SIZE_Y = None

    # Get XY positions, set in MDA window in MM
    def get_xy_positions(self):

        studio = Studio()

        # pull current MDA window positions
        acq_manager = studio.acquisitions()
        acq_settings = acq_manager.get_acquisition_settings()
        position_list_manager = studio.positions()
        position_list = position_list_manager.get_position_list()
        number_positions = position_list.get_number_of_positions()
        xy_positions = np.empty((number_positions,2))

        # iterate through position list to extract XY positions    
        for idx in range(number_positions):
            pos = position_list.get_position(idx)
            for ipos in range(pos.size()):
                stage_pos = pos.get(ipos)
                if (stage_pos.get_stage_device_label() == 'XYStage'):
                    xy_positions[idx,:] = [stage_pos.x, stage_pos.y]

        return xy_positions

    # Just before capturing an image
    def post_hardware_hook_fn(self, event):
        
        return event

    # After capturing an image
    def image_process_fn(self, image, metadata):

        return image, metadata

    def run_acquisition(self):
        
        self.PIXEL_SIZE = 1
        self.STORAGE_DIRECTORY = r'D:\\data\\sample'

        self.TILE_SIZE_X = 512
        self.TILE_SIZE_Y = 512

        os.makedirs(self.STORAGE_DIRECTORY, exist_ok=True)

        xy_positions = self.get_xy_positions()
        self.NUM_TILES = xy_positions.shape[0]
        assert self.NUM_TILES == 1

        num_time_points = 3
        time_per_slice = float(24) 
        time_interval_s = [0.0]
        time_interval_s = time_interval_s + [time_per_slice]* (num_time_points - 1)

        self.core = Core()

        with Acquisition(directory=self.STORAGE_DIRECTORY, name='pycromanager_acq', image_process_fn=self.image_process_fn, post_hardware_hook_fn=self.post_hardware_hook_fn) as acq:
            events = multi_d_acquisition_events(xy_positions=xy_positions, num_time_points=num_time_points, time_interval_s=time_interval_s)
            acq.acquire(events)

if __name__ == '__main__':
    acquisition = acquisition()
    acquisition.run_acquisition()
```

If there is any additional information I can provide, please do let me know. Thanks.

**Comment by henrypinkard** [comment]
I had to change `time_interval_s` to equal `4` since the list isnt merged yet, and I was not able to reproduce running it. Are you using the latest nightly build of MM?

**Comment by ckolluru** [comment]
My bad, I uninstalled and reinstalled pycromanager so that it does not have my changes to allow ```time_interval_s``` to be a list. I also updated Micromanager to the latest nightly build.

I don't see this exception thrown now after the acquisition is complete. Looking at the python file that was giving this exception earlier (```socket.py``` line 735), can we assume that it was from the older MM build and not the changes I was making to accomodate ```time_interval_s``` as a list?  I had a few calls to isinstance().

There are couple of other issues that I'm facing now that I wanted to point out. This is with the latest builds of pycromanager and MM, demo config, one position provided in the position list in MM's MDA window.

This is the code I'm running.

```
import numpy as np
import time
from pycromanager import Acquisition, Studio, multi_d_acquisition_events, Core
import os

class acquisition():
    def __init__(self):
        self.core = None

        self.NUM_TILES = 1
        self.PIXEL_SIZE = 0
        self.STORAGE_DIRECTORY = None
        self.TILE_SIZE_X = None
        self.TILE_SIZE_Y = None

    # Get XY positions, set in MDA window in MM
    def get_xy_positions(self):

        studio = Studio()

        # pull current MDA window positions
        acq_manager = studio.acquisitions()
        acq_settings = acq_manager.get_acquisition_settings()
        position_list_manager = studio.positions()
        position_list = position_list_manager.get_position_list()
        number_positions = position_list.get_number_of_positions()
        xy_positions = np.empty((number_positions,2))

        # iterate through position list to extract XY positions    
        for idx in range(number_positions):
            pos = position_list.get_position(idx)
            for ipos in range(pos.size()):
                stage_pos = pos.get(ipos)
                if (stage_pos.get_stage_device_label() == 'XYStage'):
                    xy_positions[idx,:] = [stage_pos.x, stage_pos.y]

        return xy_positions

    # Just before capturing an image
    def post_hardware_hook_fn(self, event):
        
        return event

    # After capturing an image
    def image_process_fn(self, image, metadata):

        return image, metadata

    def run_acquisition(self):
        
        self.PIXEL_SIZE = 1
        self.STORAGE_DIRECTORY = r'D:\\data\\sample'

        self.TILE_SIZE_X = 512
        self.TILE_SIZE_Y = 512

        os.makedirs(self.STORAGE_DIRECTORY, exist_ok=True)

        xy_positions = self.get_xy_positions()
        self.NUM_TILES = xy_positions.shape[0]
        assert self.NUM_TILES == 1

        num_time_points = 4
        time_interval_s = 4

        self.core = Core()

        with Acquisition(directory=self.STORAGE_DIRECTORY, name='pycromanager_acq', image_process_fn=self.image_process_fn, post_hardware_hook_fn=self.post_hardware_hook_fn) as acq:
            events = multi_d_acquisition_events(xy_positions=xy_positions, num_time_points=num_time_points, time_interval_s=time_interval_s)
            acq.acquire(events)

if __name__ == '__main__':
    acquisition = acquisition()
    acquisition.run_acquisition()
```

Sometimes I get this error below (same as https://forum.image.sc/t/failure-when-using-pycromanager-for-dual-camera-acquisition-with-different-frame-rates/81578?u=chaitanya_kolluru)
```
Traceback (most recent call last):
  File "C:\Users\MUSE\Desktop\muse-pycromanager\minimal.py", line 74, in <module>
    acquisition.run_acquisition()
  File "C:\Users\MUSE\Desktop\muse-pycromanager\minimal.py", line 68, in run_acquisition
    with Acquisition(directory=self.STORAGE_DIRECTORY, name='pycromanager_acq', image_process_fn=self.image_process_fn, post_hardware_hook_fn=self.post_hardware_hook_fn) as acq:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MUSE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\acquisitions.py", line 348, in __init__
    summary_metadata = ndtiff_storage.get_summary_metadata()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MUSE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 480, in <lambda>
    ): instance._translate_call(signatures_list, args, static=_java_class == 'java.lang.Class')
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MUSE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 694, in _translate_call
    recieved = self._receive()
               ^^^^^^^^^^^^^^^
  File "C:\Users\MUSE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 587, in _receive
    return self._get_bridge()._receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MUSE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 335, in _receive
    return self._main_socket.receive(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MUSE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 183, in receive
    self._check_exception(message)
  File "C:\Users\MUSE\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pycromanager\zmq_bridge\_bridge.py", line 188, in _check_exception
    raise Exception(response["value"])
Exception: java.lang.NullPointerException
org.micromanager.ndtiffstorage.NDTiffStorage.getSummaryMetadata(NDTiffStorage.java:1088)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.micromanager.internal.zmq.ZMQServer.runMethod(ZMQServer.java:405)
org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:483)
org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

Other times, the pycromanager acquisition window opens but no image is seen. The window says that the acquisition is Running. Is there a requirement that previous acquisition windows be closed prior to running a pycromanager script?

Some times things work as expected. I'm not sure how to analyze these two issues further.

Thanks,
Chaitanya

**Comment by ckolluru** [comment]
So one way to reproduce the error with the blank acquisition window seems to be this.

1. Open MM, demo config, place one position in the list 
2. Run the python script provided here, ensure that path in STORAGE_DIRECTORY is empty.
3. The acquisition should finish in a few seconds. Close the window and wait for a few seconds.
4. Run the python script again. Repeat steps 2-3 a couple of times.
5. Close MM and reopen with demo config and a position in the list.
6. Run the python script again, it results in a blank acquisition window for me. The menu bar will say that the acquisition is (Running).

**Comment by henrypinkard** [comment]
> I don't see this exception thrown now after the acquisition is complete. Looking at the python file that was giving this exception earlier (`socket.py` line 735), can we assume that it was from the older MM build and not the changes I was making to accomodate `time_interval_s` as a list?

Yes definitely

The nullpointer issue I think is a race condition where the python side was asking for something about the dataset, but this thing was initialized a different thread so it wasnt always ready and threw that exception. I think [this change](https://github.com/micro-manager/NDTiffStorage/pull/115) should fix it. You can give it try by either downloading the nighly after all the changes go through, or by replacing the current NDTiff jar file in the `micro-mananger/plugins` directory with the new one, which will be available [here](https://s01.oss.sonatype.org/#nexus-search;quick~micro-manager)

> Is there a requirement that previous acquisition windows be closed prior to running a pycromanager script?

> Are there known issues with writing NDTIFF to pre-existing directories which have previous acquisitions in sub-dirs?

Shouldnt be.

Not sure about this second bug. Worth seeing if this persists after the above fix. That status bar thing is especially weird. Not sure why the XYstage would be set to a crazy value like that.

**Comment by ckolluru** [comment]
I've installed the latest nightly build of MM (2023/05/30). The error with the blank acquisition window still exists, it seems to happen when I finish the acquisition from pycromanager and run the same acquisition again but quickly.

The stage coordinates also remain weird.
![image](https://github.com/micro-manager/pycro-manager/assets/8373968/364f9916-aee8-47d4-9794-2fa4bcd01d22)

**Comment by henrypinkard** [comment]
Is the Null pointer error fixed now?


> I downloaded the latest version of NDTiffStorage jar (v 2.12.1). and replaced it in the `micro-manager/plugins` directory.

Did you need to do this even after downloading the nightly build? I would think it would already be in there but if not it might indicate something wrong with the build system.

I'm a bit confused as to what exactly is going wrong, since this thread has touched on multiple things in different versions. Can you write a minimal test example with the demo config that reliably reproduces the error and describe exactly what is going wrong?

**Comment by ckolluru** [comment]
> Is the Null pointer error fixed now?

Yes, I do not see that error now after the latest build of MM. I will keep testing because the workflow that resulted in the error did not seem to be consistent.

> Did you need to do this even after downloading the nightly build? I would think it would already be in there but if not it might indicate something wrong with the build system.

Yes, I checked this again. If I install the latest nightly build of MM (2023/05/30) from [here](https://download.micro-manager.org/nightly/2.0/Windows/), I have NDTiffStorage-2.12.0.jar in \path\to\Micro-Manager-2.0gamma\plugins\Micro-Manager\

> Can you write a minimal test example with the demo config that reliably reproduces the error and describe exactly what is going wrong?

Will do shortly. I can open a new issue once the workflow that is causing this issue is more clear to me.

Thanks,
Chaitanya

**Comment by henrypinkard** [comment]
> Yes, I checked this again. If I install the latest nightly build of MM (2023/05/30) from [here](https://download.micro-manager.org/nightly/2.0/Windows/), I have NDTiffStorage-2.12.0.jar in \path\to\Micro-Manager-2.0gamma\plugins\Micro-Manager\

It looks like the auto buidl system failed to update for some reason again. I just pushed through a fix https://github.com/micro-manager/pycro-manager/pull/607. Thanks for checking

> > Can you write a minimal test example with the demo config that reliably reproduces the error and describe exactly what is going wrong?
> 
> Will do shortly. I can open a new issue once the workflow that is causing this issue is more clear to me.

Sounds good
