### ISSUE TITLE
Launching headless mode with no configuration file

### ISSUE THREAD

**Issue by jacopoabramo** [micro-manager/pycro-manager#698]
Greetings,

I'm trying a small snippet code to launch Pycro-Manager in headless mode without any pre-loaded configuration file. By doing so I'm aiming to then use an instance of the Micro-Manager core to dynamically load my list of devices via the `load_device` function. From the `start_headless` string-doc this seems possible by setting `config_file=None`; when I do this though, as follows: 

```py
from pycromanager import Core, start_headless
from pymmcore_plus import find_micromanager 

import logging

logging.basicConfig(level=logging.INFO)

logger = logging.getLogger()

mm_app_path = find_micromanager()

logger.info("Found Micro-Manager at: " + mm_app_path)

config_file = mm_app_path + "/MMConfig_demo.cfg"

# Start the Java process
start_headless(mm_app_path, config_file=None, debug=True)

logger.info("Started Micro-Manager headless, creating core... ")

core = Core()

logger.info("Done")
```

This traceback is produced:

```py
Traceback (most recent call last):
  File "pycromanager_core_sandbox.py", line 15, in <module>
    start_headless(mm_app_path, config_file=None, debug=True)
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python38\lib\site-packages\pycromanager\headless.py", line 174, in start_headless
    process = subprocess.Popen(
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1251, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 553, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python38\lib\os.py", line 818, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

At the same time, if I just leave `config_file=''` as default parameter, this is the traceback I get:

```
Traceback (most recent call last):
  File "pycromanager_core_sandbox.py", line 15, in <module>
    start_headless(mm_app_path, config_file='', debug=True)
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python38\lib\site-packages\pycromanager\headless.py", line 200, in start_headless
    raise Exception('Error starting headless mode')
Exception: Error starting headless mode
```

Python version: 3.8.10
Pycro-Manager version: 0.29.1
OS: Windows 10
MM Studio version: 2.0.3 20230912
MMCore version 10.5.0
Device API version 71, Module API version 10

Thanks in advance

**Comment by henrypinkard** [comment]
Definitely a bug. Fixed in https://github.com/micro-manager/pycro-manager/compare/main...henrypinkard:main?body=&expand=1&title=start+headless+mode+with+no+config I think. Haven't had a chance to test it yet though. This requires both the new nightly build and new pip version

**Comment by jacopoabramo** [comment]
Hi @henrypinkard , just tested with the same script from #672 but nothing changes, I get the same traceback as before even with the hotfixes.

**Comment by henrypinkard** [comment]
There was still a remaining issue with a discrepency between setting `config_file=''` (which works) and `config_file=None` which failed. Once #700 merges, either way should work

**Comment by jacopoabramo** [comment]
hi @henrypinkard , i'm sorry but this still does not work. To be fair I tested this with another python version (3.10), but I assumed this was no issue since it should be supported as well.

**Comment by jacopoabramo** [comment]
Okay, so I added the Micro-Manager path as hardcoded string (I would love to have something like `find_micromanager` available in Pycro-Manager as well though), and updated Micro-Manager with the latest nightly build. Below the reference script:

```py
from pycromanager import Core, start_headless, stop_headless
from pymmcore_plus import find_micromanager 

import logging

logging.basicConfig(level=logging.INFO)

logger = logging.getLogger()

mm_app_path = "C:\\Program Files\\Micro-Manager-2.0"

logger.info("Found Micro-Manager at: " + mm_app_path)

# Start the Java process
start_headless(mm_app_path, config_file="")

logger.info("Started Micro-Manager headless, creating core... ")

core = Core()

logger.info("Done")
```

This seems to work but after the script ends the traceback generates the following:

```
Exception ignored in: <function _JavaObjectShadow.__del__ at 0x000002D77FF4B760>
Traceback (most recent call last):
  File "C:\Users\jacop\AppData\Local\Programs\Python\Python310\lib\site-packages\pycromanager\zmq_bridge\bridge.py", line 657, in __del__
TypeError: 'NoneType' object is not callable
```

It is not a great issue but I am curious of what is causing this

**Comment by jacopoabramo** [comment]
Anyway closing the issue as now it´s working as intended

**Comment by henrypinkard** [comment]
> Also, what would be the best way to verify the compatibility with the current version of Pycro-Manager and MMStudio?

I aim to put in checks that avoid any backwards incompatibilities, and ideally the automated tests should catch this. In some cases I'll also update the expected version numbers to print a warning when things are out of date (I didn't do that here, but just added it https://github.com/micro-manager/pycro-manager/pull/703).

In general, the safest policy is to stick with the latest versions of both.

**Comment by jacopoabramo** [comment]
I'm reopening the issue only to request if it's possible to adapt this change also when calling `start_headless` with `python_backend=True`, since for my implementation to keep backwards compatibility I may reverse to use pymmcore instance and at this time the function due to the fact that it expects `config_file` to be not an empty string.

**Comment by henrypinkard** [comment]
Makes sense. You should feel free to just open PRs to fix small things like this
